const items = [
  {
    id: 1,
    name: "Cashew Butter",
    image1: "/images/Product-images/cashew-butter.jpg",
    image2:"https://websitedemos.net/organic-shop-02/wp-content/uploads/sites/465/2018/06/cashew-butter-500.jpg",
    price: 25,
    category: "Groceries",
  },
  {
    id: 2,
    name: "Assorted Coffee",
    image1: "/images/Product-images/coffee.jpg",
    image2:"https://websitedemos.net/organic-shop-02/wp-content/uploads/sites/465/2018/06/coffee-asorted.jpg",
    price: 35,
    category: "Groceries",
  },
  {
    id: 3,
    name: "Diabetic Cookies",
    image1: "/images/Product-images/diabetic-cookies.jpg",
    image2:"https://websitedemos.net/organic-shop-02/wp-content/uploads/sites/465/2018/06/diabetic-cookies.jpg",
    price: 25,
    category: "Groceries",
  },
  {
    id: 4,
    name: "Natural Extracted Edible Oil",
    image1: "/images/Product-images/edible-oil.jpg",
    image2:"https://websitedemos.net/organic-shop-02/wp-content/uploads/sites/465/2018/06/edible-oil.jpg",
    price: 34,
    category: "Groceries",
  },
  {
    id: 5,
    name: "Farm Fresh Eggs",
    image1: "/images/Product-images/eggs.jpg",
    image2:"https://websitedemos.net/organic-shop-02/wp-content/uploads/sites/465/2018/06/eggs.jpg",
    price: 19,
    category: "Groceries",
  },
  {
    id: 6,
    name: "Organic Face scrub",
    image1: "/images/Product-images/face-wash.jpg",
    image2:"https://websitedemos.net/organic-shop-02/wp-content/uploads/sites/465/2018/06/face-wash.jpg",
    price: 30,
    category: "Groceries",
  },
  {
    id: 7,
    name: "Fresh Orange Juice",
    image1: "/images/Product-images/orage-juice.jpg",
    image2:"https://websitedemos.net/organic-shop-02/wp-content/uploads/sites/465/2018/06/orage-juice-kariz.jpg",
    price: 28,
    category: "Juice",
  },
  {
    id: 8,
    name: "Fresh Organic Honey",
    image1: "/images/Product-images/organic-honey.jpg",
    image2:"https://websitedemos.net/organic-shop-02/wp-content/uploads/sites/465/2018/06/organic-honey.jpg",
    price: 40,
    category: "Groceries",
  },
  {
    id: 9,
    name: "Pulses From Organic Farm",
    image1: "/images/Product-images/pulses.jpg",
    image2:"https://websitedemos.net/organic-shop-02/wp-content/uploads/sites/465/2018/06/pulses.jpg",
    price: 55,
    category: "Groceries",
  },
  {
    id: 10,
    name: "Handpicked Red Chillies",
    image1: "/images/Product-images/red-chillies.jpg",
    image2:"https://websitedemos.net/organic-shop-02/wp-content/uploads/sites/465/2018/06/red-chillies.jpg",
    price: 19,
    category: "Groceries",
  },
  {
    id: 11,
    name: "Hand Sanitizer",
    image1: "/images/Product-images/sanitizer.jpg",
    image2:"https://websitedemos.net/organic-shop-02/wp-content/uploads/sites/465/2018/06/sanitizer.jpg",
    price: 15,
    category: "Groceries",
  },
  {
    id: 12,
    name: "Wheat From Organic Farms",
    image1: "/images/Product-images/wheat.jpg",
    image2:"https://websitedemos.net/organic-shop-02/wp-content/uploads/sites/465/2018/06/wheat.jpg",
    price: 50,
    category: "Groceries",
  },
];

export default items;
